// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ZTFY3o6qpLPV-Ccbr_31CTHA6tlrG08',
    appId: '1:730392440608:web:78e1082c7b7805647e3145',
    messagingSenderId: '730392440608',
    projectId: 'coffix-app-prod',
    authDomain: 'coffix-app-prod.firebaseapp.com',
    storageBucket: 'coffix-app-prod.firebasestorage.app',
    measurementId: 'G-L0QHWGVVZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzcRDAKeVfQkfcYSQD93hAi0w9EYtoJfQ',
    appId: '1:730392440608:android:985cf971e07786b37e3145',
    messagingSenderId: '730392440608',
    projectId: 'coffix-app-prod',
    storageBucket: 'coffix-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Jwe7I7MkFnoP17JJEjxoFFQQyoiPJOs',
    appId: '1:730392440608:ios:0cba47268ac686e77e3145',
    messagingSenderId: '730392440608',
    projectId: 'coffix-app-prod',
    storageBucket: 'coffix-app-prod.firebasestorage.app',
    iosBundleId: 'com.example.coffixApp',
  );
}
