// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGN7-y80VIWuCBsoAjmMlsq9a7K-WqkIs',
    appId: '1:659645318299:web:b84bb7f22b6e83a211323e',
    messagingSenderId: '659645318299',
    projectId: 'coffix-app-dev',
    authDomain: 'coffix-app-dev.firebaseapp.com',
    storageBucket: 'coffix-app-dev.firebasestorage.app',
    measurementId: 'G-KND99Y5YT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxqMVJ4LWb9oSp8apHxCLYVeeE_5pmnGc',
    appId: '1:659645318299:android:57e7148f7de0c4fa11323e',
    messagingSenderId: '659645318299',
    projectId: 'coffix-app-dev',
    storageBucket: 'coffix-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM7u28RaKQIFhjuQ_fhDEuu864mviDlTM',
    appId: '1:659645318299:ios:42dcd84c6a557c0111323e',
    messagingSenderId: '659645318299',
    projectId: 'coffix-app-dev',
    storageBucket: 'coffix-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.coffixApp',
  );
}
